{% set name = "vispy" %}
{% set version = "0.7.1" %}
{% set sha256 = "27356eeace5916b44486fae8a26ba56492461e07e03ddaf994ab9931be77bd54" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - fontconfig  # [unix]
    - numpy
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - fontconfig  # [unix]
    - freetype-py
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - vispy

about:
  home: http://vispy.org
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: VisPy is a high-performance interactive 2D/3D data visualization library.
  dev_url: https://github.com/vispy/vispy
  doc_url: http://vispy.org/documentation.html
